### ISSUE TITLE
Maven Central Migration

### ISSUE THREAD

**Issue by ryanb-saltech** [DimaDake/billing#2]
Can you move this to Maven Central because JCenter is no longer receiving support and is deprecated in newer versions of gradle? Thanks!

**Comment by DimaDake** [comment]
The library is quite outdated. Do you actually want to use it or have any other reasons to move it? I suppose you may want to use this https://developer.android.com/google/play/billing/developer-payload#attribute instead of developer payload.

**Comment by ryanb-saltech** [comment]
Actually, I don't think I need it anymore. It was part of an old dependency but it was changed and isn't in use anymore. I've been going through and updating them because of the JCenter change and I thought we still needed it. Thanks for your help!
